name: Bazel Build and Test

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: macos-14

        steps:
          - uses: actions/checkout@v2
          - uses: bazel-contrib/setup-bazel@0.8.1
            with:
                # Avoid downloading Bazel every time.
                bazelisk-cache: true
                # Store build cache per workflow.
                disk-cache: ${{ github.workflow }}
                # Share repository cache between workflows.
                repository-cache: true
          - run: bazelisk build --config=default_cpp20 //...
          - run: bazelisk test --config=default_cpp20 //...
